### ISSUE TITLE
Click query status legend marks to filter chart.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#12]
from @agstn

**Comment by jwildfire** [comment]
Test Notes: Click the status in the legend to filter the chart.

**Comment by jwildfire** [comment]
@brittsikora ready for testing in CAT with version = 'v1.0.0-dev' and data = 'queries/queries.csv'

**Comment by brittsikora** [comment]
Expected Result: Selected a query status from the legend and the chart filtered on it. 

Outcome: Pass

Note: I used Ctrl+click to select all statuses and they all reappeared, but it would be nice to have a "clear" button to reset the chart after using this function,
