### ISSUE TITLE
Add hover text definitions for each column in listing.

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/query-overview#126]
Heather requested this 12/17/18 and is working on creating definitions for each of the columns in the listing/ She wants these to display when the user hovers over the column header

# Test notes
* Listing column headers have tooltips.

**Comment by samussiah** [comment]
@pburnsdata , did Heather ever send these definitions?

**Comment by samussiah** [comment]
Variable | Description
-- | --
Subjectnameoridentifier | Subject ID assigned in Rave
Sitename | Site name assigned in Rave
Folderinstancename | Name of folder currently displayed in Rave. If the folder   was renamed (e.g. append a date) this will be reflected here
Folderoid | Folder OID as assigned in Architect
formoid | Form OID as assigned in Architect
Ecrfpagename | Name of the form currently displayed in Rave. If the form   was renamed (e.g. append a date) this will be reflected here
Fieldname | Field name as assigned in Architect
Querystatus | Status of query in Rave. Options include: Open, answered,   closed, cancelled
Queryopenby | Entity opening the query (System or name of individual)
Querytext | Text of query
Queryresponsetext | Site response to the query
Markinggroup | Group opening the query. Options include: CRA, DM, Safety,   System
Fieldlabel | Field label as assigned in Architect
Queryopendate | Date query was opened in the system
Queryresolveddate | Date query was closed
Queryresponsedate | Date query was responded to by the site
Qdays | Number of days the query has been/was open. Number of days   from date opened to answered or for queries open the number of days from date   opened to data extraction date
Open_time | Number of days from when the query was opened to the data   extraction date. This is populated for all queries (e.g. open and closed).   Options include: Last 7, 14, and 30 days)

**Comment by emmorris** [comment]
Note that the hover text for each variable should match those provided by Heather (see the table in the comment above).  However, for text that included "Rave" it should say "EDC" instead since that is more generic.
