### ISSUE TITLE
Sync Query Age and Query Status filters.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#127]
so that, for instance, deselecting _Closed_ in one deselects _Closed_ in the other.

# Test notes
* Selecting or deselecting a Query Age filter option should select or deselect the corresponding option in the Query Status filter, and vice versa.  For instance, selecting a Query Age category of _Answered_ should select the Query Status category of _Answered_.
* The legend filter should behave the same, i.e. the legend filter should update as the filters update and the filters should update as the legend updates.
* The Select/Deselect All checkboxes should update as expected for both filters.
* The _Open_ query status is an exception as it maps to multiple Query Age categories.  Selecting _0-2 wks_ in Query Age should select _Open_ in Query Status, but deselecting a single _Open_ Query Age category should not deselect _Open_.

**Comment by emmorris** [comment]
This was requested by Heather on 12-17-18.
