### ISSUE TITLE
Add max width to filters.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#139]
to prevent long values in filter options from overlapping the controls container.  might be worth implementing a proper multi-select (captured in #140)

# Test notes
* Edit the data file by adding a really long value to the _sitename_ column, like 100 characters or so.
* Upload the data file, render the chart, and verify that the _Site_ filter does not overlap the edge of the controls.
* Verify that the options in the filters have tooltips.

**Comment by danedexF5** [comment]
Approved
