### ISSUE TITLE
Remove "Field" from group by control

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/query-overview#16]
Just use form field. Will also need to update clickable y-axis a bit.

**Comment by jwildfire** [comment]
Also add a title for "Form: Field" if either `formDetails_col` or `fieldDetails_col` is specified. Builds upon #8

**Comment by jwildfire** [comment]
Test Notes - Confirm that "Field" is no longer in the "group by" dropdown, and that the y-axis labels have reasonable tooltip information when "group by" is set to "Form" or "Form: Field". Branch is `v1.0.0-dev` (@brittsikora)

**Comment by brittsikora** [comment]
Are there any settings I need to use to see this?

**Comment by samussiah** [comment]
Nope, it's default functionality.

**Comment by brittsikora** [comment]
Okay, Field is still showing up in my Group by drop-down
![16](https://cloud.githubusercontent.com/assets/14914918/25862836/709d19b8-34b7-11e7-91a2-b1ae307c3f5f.png)

and tooptips aren't showing up at all - I used settings to get them last time

**Comment by brittsikora** [comment]
Used newer commit: 06461b386adbb6ff682826873ecc8ea8103c5333

Expected result: Group by drop down no longer displays Field as a filter option. And when I grouped by form and form: field, the tooltips displayed appropriately.

Outcome: Pass

![16](https://cloud.githubusercontent.com/assets/14914918/25873229/b008a5b2-34db-11e7-9fe9-d3560cf598b1.png)
![16_3](https://cloud.githubusercontent.com/assets/14914918/25873231/b0f374ac-34db-11e7-9e1d-8ae82999d78d.png)
![16_2](https://cloud.githubusercontent.com/assets/14914918/25873232/b1b7caaa-34db-11e7-8a4b-b929313e8ffd.png)
