### ISSUE TITLE
Improve annotated counts when bar arrangement is set to 'grouped'.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#18]
Specifically offset vertically as a function of both `y.rangeBand()` and the associated query status as it appears in the query status order.

**Comment by jwildfire** [comment]
Test Notes: Confirm that numeric bar values are positioned appropriately when arrangement = "grouped". Branch = `v1.0.0-dev`

**Comment by jwildfire** [comment]
@brittsikora  ready for your QC

**Comment by brittsikora** [comment]
Expected Result: Change bar arrangement to "grouped". Bar value numbers look appropriate.

Outcome: Pass

![18](https://cloud.githubusercontent.com/assets/14914918/25858740/73f2f40a-34aa-11e7-9fb2-698fa85895a8.JPG)
