### ISSUE TITLE
Add Visit Filter

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/query-overview#2]
Can we add a Visit filter to the graphic? Given how Rave handles folder renaming this could potentially be a bit unwieldy, but I'll look at streamlining the .csv before it gets to the graphic.

(Request from Derek via email on 5/24/16)

**Comment by jwildfire** [comment]
Test Case: In CAT make sure a visit filter appears with the settings that @samussiah provides below.

**Comment by samussiah** [comment]
```javascript
{
    "filters": [ 
        {
            "value_col": "visit",
            "label": "Visit"
        }
    ]
}
```

**Comment by jwildfire** [comment]
@brittsikora ready for testing in CAT with version = 'v1.0.0-dev' and data = 'queries/queries.csv'

**Comment by brittsikora** [comment]
Expected Result: Load the chart with the settings above to render a visit filter.

Outcome: Pass
![2](https://cloud.githubusercontent.com/assets/14914918/25725516/5e690c7e-30ee-11e7-9da9-de317d11b952.JPG)

**Comment by brittsikora** [comment]
New settings are: {
"filters": [
{
"value_col": "Visit/Folder",
"label": "Visit"
}
]
}
