### ISSUE TITLE
Add Reset Button

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#21]
Add button to reset chart to default

**Comment by samussiah** [comment]
Test notes: confirm that all controls reset, the chart returns to its initial layout, the listing disappears, and no extraneous elements are present on the webpage.

**Comment by brittsikora** [comment]
Should I use ad0a160 or v1.0.0-dev to test?

**Comment by samussiah** [comment]
Yeah, I bet the cache of _v1.0.0-dev_ hasn't updated since merging the recent pull requests.  You should be able to use ad0a16053141d513ca08efaa4f883a5f12a0a616 instead.

**Comment by brittsikora** [comment]
Awesome, I will use ad0a160 then.

Expected Outcome: I used the controls and filters to show pieces of the data and then hit the reset button to return the chart to the default.

Outcome: Pass

![21_1](https://cloud.githubusercontent.com/assets/14914918/25863574/5a4614d2-34ba-11e7-8f89-07a805cbce88.JPG)
![21_2](https://cloud.githubusercontent.com/assets/14914918/25863576/5b0ad312-34ba-11e7-89be-270d9bffbfe5.JPG)
