### ISSUE TITLE
Changing `config.cutoff` doesn't affect _Show first N groups_ control.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#23]
Specifying 25 results in 25 groups being displayed but 10 is still selected in the control.  Specifying "All" doesn't render anything.

Suggest pushing the `cutoff` argument to the _Show first N groups_ control's `values` array if the argument isn't one of 10/25/"All" and setting the control's checked radio button to `cutoff`.  An argument of `All` should map to the number of groups in the data.

**Comment by samussiah** [comment]
Test notes: confirm that setting the `cutoff` argument to one of the defaults, e.g.:
```javascript
{"cutoff": 25}
```
sets to active the appropriate radio button in the _Show first N groups_ control and setting the `cutoff` argument to something other than one of the defaults, e.g.:
```javascript
{"cutoff": 99}
```
adds that option to the _Show first N groups_ control.

**Comment by jwildfire** [comment]
The custom `{cutoff:99}` functionality is 👌!

**Comment by brittsikora** [comment]
Expected Result: I entered in the custom setting for 25 groups and the default was set to 25. I entered in the custom setting for 99 groups and the default was set to 99.

Outcome: Pass
![23](https://cloud.githubusercontent.com/assets/14914918/25873031/d9d3f0b4-34da-11e7-8a04-51cf51e22baa.JPG)
![23_2](https://cloud.githubusercontent.com/assets/14914918/25873032/dad93c9e-34da-11e7-99d7-ed8a1b296ea3.JPG)
