### ISSUE TITLE
Y-axis formatting tweak

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/query-overview#24]
Make the y-axis labels look like links (blue+underline) when they are clickable.

**Comment by jwildfire** [comment]
Test Notes: Confirm that the form is updated when grouped by form

**Comment by brittsikora** [comment]
Expected Outcome: The labels on the y-axis that are clickable now look like links

Result: Pass

![24](https://cloud.githubusercontent.com/assets/14914918/25873309/fe3249d2-34db-11e7-84aa-f2fb1124de6a.JPG)
