### ISSUE TITLE
Update default settings

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/query-overview#30]
Add the following:
- include Site in "Group by" control
- include Site and Marking Group as standard filters.

**Comment by jwildfire** [comment]
Went ahead and added Marking group to the group by control as well.

**Comment by jwildfire** [comment]
Test Notes: Confirm that the new filters and group by options show up and function as expected. Commit: 0285d7f0d6f3f06fe4c8b01730050ab7c8034b68

**Comment by jwildfire** [comment]
@brittsikora ready for testing.

**Comment by brittsikora** [comment]
Expected Outcome: View the new commit and make sure group by site, filter by site, and filter by marking group are there and work as expected

Result: Pass
![30](https://cloud.githubusercontent.com/assets/14914918/25968988/5a907042-3661-11e7-9644-d2355210fac8.png)
