### ISSUE TITLE
Remove Marking Group from Default Filters

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/query-overview#32]
The marking group filter disappears when I enter the settings for the visit filter - we want to make the marking group filter a customization

**Comment by jwildfire** [comment]
Also removing site from the default filters.

**Comment by jwildfire** [comment]
Testing notes: No visit and marking groups should show up with default settings, but they should appear with settings below. 

```
{
    "filters": [
        {
            "value_col": "Visit/Folder",
            "label": "Visit"
        },
        {
          "value_col": "Query Open By: Marking Group",
          "label": "Marking Group"
        }
    ]
}
```

**Comment by brittsikora** [comment]
Expected Outcome: Entering the above settings will render the marking group and visit filters

Result: Pass
![32](https://cloud.githubusercontent.com/assets/14914918/26116665/f4c3b786-3a31-11e7-85ce-5e03ff59c331.JPG)
