### ISSUE TITLE
Add export to .csv for links table

### ISSUE THREAD

**Issue by emmorris** [RhoInc/query-overview#34]
Not urgent

**Comment by jwildfire** [comment]
Test Notes: With the setting on (`{"exportData":true}`), a "Download Query Data" link should appear under the reset chart button. Check that the data exported matches the raw data (Data in CAT is found [here](https://github.com/RhoInc/viz-library/blob/master/data/queries/queries.csv)), and that filters are applied as expected in the downloaded data.

**Comment by brittsikora** [comment]
Works in v1.1.0-dev

![34](https://user-images.githubusercontent.com/14914918/28322671-b5ba84c6-6ba4-11e7-837f-4ccdd157971d.JPG)
Pass
