### ISSUE TITLE
Legend filter has a bug.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#36]
in [src/chart/onResize.js](https://github.com/RhoInc/query-overview/blob/master/src/chart/onResize.js):

```
      chart.filters
        .filter(filter => filter.col !== chart.config.status_col)
        .forEach(filter => {
          if (filtered === false && filter.val !== "All")
            filtered =
              d[filter.col] !== filter.val ||
              filter.val.indexOf(d[filter.col]) === -1;
        });
```

update to treat string and array `filter.val` values independently:

```
        chart.filters.filter(function (filter) {
          return filter.col !== chart.config.status_col;
        }).forEach(function (filter) {
          if (filtered === false && filter.val !== "All")
                filtered = typeof filter.val === 'string'
                    ? d[filter.col] !== filter.val
                    : filter.val.indexOf(d[filter.col]) === -1;
        });
```

**Comment by jwildfire** [comment]
@samussiah Want to make a quick v1.0.1 branch and put this put a a bug fix release?

**Comment by jwildfire** [comment]
Test Notes: Error was occurring when a different filter was applied (e.g. site). To confirm functionality, filter on site and then filter using the Query Status Legend. No chart is rendered in v1.0, but should work as expected in `legend-filter-bug` branch.

**Comment by brittsikora** [comment]
The chart is rendering using v1.0.0-RC1

Pass

![36](https://user-images.githubusercontent.com/14914918/28322617-8b7c99c4-6ba4-11e7-93ac-55d2182c0f07.JPG)
