### ISSUE TITLE
Form: Field shows up in the listing after resetting.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#37]
Remove _Form: Field_ from listing columns.

**Comment by jwildfire** [comment]
Test Notes: Click Reset, then Click a bar to create a listing. No column for "Form:Field" should be shown, but "Form:Field" should still be an option in the Group By Dropdown

**Comment by brittsikora** [comment]
Tested using 1.1.0-dev

Pass

![37](https://user-images.githubusercontent.com/14914918/28323088-d125ee84-6ba5-11e7-85ef-41cfeb248f45.JPG)
