### ISSUE TITLE
Improve filter placement.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#40]

**Comment by jwildfire** [comment]
Test Notes: "Group By" first, then filters, then other controls. Test with a custom filter added as well: 
`{"filters":[{"value_col": "Visit/Folder", "label": "Visit"}]}`

**Comment by brittsikora** [comment]
Tested using dev and RC1

Pass

![41](https://user-images.githubusercontent.com/14914918/28323405-af2e6f12-6ba6-11e7-82c5-64bf51dd2dac.JPG)
