### ISSUE TITLE
In Internet Explorer moveToFront causes unexpected behavior in bar event listeners.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#41]
Avoid calling in Internet Explorer.

**Comment by jwildfire** [comment]
Test Notes: Clicking bars to create listings (multiple times) should work as expected after this fix.

**Comment by brittsikora** [comment]
Tested using v1.1.0-dev

Pass

![41](https://user-images.githubusercontent.com/14914918/28323282-52615a24-6ba6-11e7-9d00-afcbcfa5eab3.JPG)
