### ISSUE TITLE
Create a linked table

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/query-overview#5]
Click on a bar get a table

**Comment by jwildfire** [comment]
Test Notes: Confirm that an associate table appears when you click a bar. The table should only have data for the status section of the bar clicked.

**Comment by jwildfire** [comment]
@brittsikora ready for testing in CAT with version = 'v1.0.0-dev' and data = 'queries/queries.csv'

**Comment by brittsikora** [comment]
Expected Result: I clicked on a bar and a linked table appeared for one section of the stacked bar

Outcome: Pass

![5](https://cloud.githubusercontent.com/assets/14914918/25725445/07eb1932-30ee-11e7-9c3c-745be07dc1fe.JPG)
