### ISSUE TITLE
query-overview not rendering anything using webcharts version v1.9.0-RC3

### ISSUE THREAD

**Issue by dschwentker** [RhoInc/query-overview#51]
In the current pending version of webcharts, I'm not seeing anything loaded when I render the chart in CAT. I see the same behavior in all browsers.

![image](https://user-images.githubusercontent.com/17090469/31505248-73eb935a-af42-11e7-9cd1-2ab7af195d7e.png)

**Comment by jwildfire** [comment]
Resolved in v1.1.1 release
