### ISSUE TITLE
ReadMe Images

### ISSUE THREAD

**Issue by mhickle** [RhoInc/query-overview#55]
![gif1](https://user-images.githubusercontent.com/31038805/34172985-d388587a-e4c1-11e7-9ca7-0b2d24de0dbc.gif)

**Comment by mhickle** [comment]
![gif1](https://user-images.githubusercontent.com/31038805/34176999-053a9302-e4d0-11e7-9e3f-2f370779af55.gif)

**Comment by mhickle** [comment]
![4](https://user-images.githubusercontent.com/31038805/34177005-0d904b6e-e4d0-11e7-9d08-80471caa9695.PNG)

**Comment by emmorris** [comment]
No development or testing involved.  Just a placeholder issue for images.
