### ISSUE TITLE
Add Export Feature

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/query-overview#57]
Current instance is missing the CSV export feature from Webcharts

# Test notes
* Verify that the listing export button displays by default.

**Comment by emmorris** [comment]
Looks like we have the export feature, but the default setting is for it to be disabled.  DMEDS has requested that it be added as a default feature.  I believe all we need to do is change the default setting to {"exportData":true}

**Comment by dschwentker** [comment]
Tested and confirmed that the CSV export option is now displayed by default (and functions as expected) in all browsers.
