### ISSUE TITLE
Add ability to see data listing for any type of filter combination using multi-select

### ISSUE THREAD

**Issue by emmorris** [RhoInc/query-overview#66]
Right now you can select one or multiple types of query status via the clickable legend, but to see the data listing you can only select one query status at a time (by clicking one bar).  The same situation applies to other filters like only being able to select one form at a time.

DMEDS would like to have the ability to see one or multiple types of query status in the data listing.  i.e. they would like to be able to see any combination of closed, cancelled, open, and answered queries in the data listing you get when you click the bar(s) in the chart.  They would also like to see any combination of filters in the data listing.  For instance, selecting "Group by" equal to "Form" and then being able to click on the bars for any combination of forms in order to have them display in the data listing below.  

# Test notes
* Verify that all data filters are now multi-select.
* Verify that multiple bars in the chart can be highlighted.

**Comment by pburnsdata** [comment]
Hey @samussiah, an easy way to allow this would be to show the listing at all times, having it reflect the currently rendered data and then you if you want to click on a bar (and maybe multiple using ctrl?) that'd write over the listing with a button to restore the listing with all the rendered data.

Are there reasons we would want to keep the listing hidden?

**Comment by samussiah** [comment]
Good idea!  No good reason to hide the listing; I think we opted for that before we had pagination in Webcharts.  Avoid CTRL, maybe just track which bars have been clicked and modify the listing accordingly.

**Comment by pburnsdata** [comment]
excelente

**Comment by dschwentker** [comment]
Tested and confirmed that all filters are now multi-select and that multiple bars in the chart can be highlighted at the same time in all browsers.
