### ISSUE TITLE
Allow different bar groupings.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/query-overview#68]
and default to query aging category

# Test notes
* A new dropdown appears that allows the user to update the bar grouping.
* Defaults to _Query Age Category_.

**Comment by pburnsdata** [comment]
@samussiah for this one, does this mean allowing custom groupings or just adding an aging grouping? For the age grouping, I'm guessing it would be based on Query Open Date, but wasn't sure how to do the groupings. Are there preexisting groups that we use or ones that make sense with what DMs(?) use this for?

**Comment by samussiah** [comment]
Start by defaulting to query aging grouping (newly added to the [queries dataset](https://raw.githubusercontent.com/RhoInc/viz-library/master/data/queries/queries.csv) in viz-library as _Query Aging Category_) with the option to group by query status.  The actual timing categories is arbitrary.

**Comment by pburnsdata** [comment]
Ah gotcha, I somehow didn't see that variable. Thank ya sir

**Comment by dschwentker** [comment]
Confirmed that the new Status Grouping dropdown is present and working and defaults to Query Age Group.
