### ISSUE TITLE
Click Form Name (on Y-axis) to see fields with most queries

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/query-overview#7]
Filters on form 
Group by form field

**Comment by jwildfire** [comment]
Test Notes: This is a fancy control activated by clicking the y-axis labels. First, group by Form, then click on y-axis tick label to subset to the selected form with group by set to "field".

**Comment by jwildfire** [comment]
@brittsikora ready for testing in CAT with version = 'v1.0.0-dev' and data = 'queries/queries.csv'

**Comment by brittsikora** [comment]
Expected Result: I grouped the data by form, selected a form label (SCRN) from the y-axis, and the chart updated to subset the form by field

Outcome: Pass
![7_2](https://cloud.githubusercontent.com/assets/14914918/25725395/c6a60298-30ed-11e7-92ed-79f6b5e3ef9a.JPG)
![7](https://cloud.githubusercontent.com/assets/14914918/25725396/c6a63894-30ed-11e7-86b7-6b2a4dd1c76c.JPG)
