### ISSUE TITLE
Add Marking Group filter back as a default filter

### ISSUE THREAD

**Issue by brittsikora** [RhoInc/query-overview#72]
When I was creating documentation for the latest release, I noticed that the Marking Group and Visit filters were missing.

# Test notes
* By default a filter labeled _Marking Group_ (and one labeled _Visit/Folder_) should appear in the controls, both multi-selects.
* The setting associated with each is _marking\_group\_col_ and _visit\_col_, and defaults to _Query Open By: Marking Group_ and _Visit/Folder_ respectively.

**Comment by emmorris** [comment]
DMEDS requested that we add a marking group filter to the chart as a default.  I believe adding back what was already there is previous versions will give them what they need.  We had just switched it to a configuration option somewhere along the way.  They would like a filter that lets the user select All, System, DM, CRA for the marking group.  That will allow the CRAs to focus on the queries they opened and the DMs to focus on the queries they opened.  

They didn't mention the missing Visit filter, so I'll ask them if that one is also important.

**Comment by dschwentker** [comment]
Tested and passed.
