### ISSUE TITLE
Sort "Query Age" column in data listing numerically 

### ISSUE THREAD

**Issue by emmorris** [RhoInc/query-overview#76]
![image](https://user-images.githubusercontent.com/23057086/42599393-169f4522-852d-11e8-86f3-6a5b03b0fb80.png)

In some cases the Query Age column doesn't sort correctly in a numerical fashion.  See the screenshot for an example.  

# Test notes
* The _Query Age_ column should sort numerically rather than alphanumerically.  All other columns should sort alphanumerically.

**Comment by dschwentker** [comment]
Confirmed that Query Age now sorts numerically in the table, but other columns still sort alphanumerically.
