### ISSUE TITLE
Enforce a standard set of Query Age Category filters

### ISSUE THREAD

**Issue by emmorris** [RhoInc/query-overview#77]
Right now the Query Age Category filters are data driven, but DMEDS has requested that we enforce a standard set of options.  Options should be:

* 0-2 weeks
* 2-4 weeks
* 4-8 weeks
* 8-16 weeks
* >16 weeks
* Closed
* Cancelled

# Test notes
* The Query Age Category filter should have seven statuses:
  * _0-2 weeks_
  * _2-4 weeks_
  * _4-8 weeks_
  * _8-16 weeks_
  * _>16 weeks_
  * _Closed_
  * _Cancelled_
* These statuses are derived in the renderer given a variable whose name defaults to _Query Age_, measured in days.

**Comment by dschwentker** [comment]
Tested and confirmed the seven statuses in the Query Age Category filter.
