### ISSUE TITLE
Add labels for field level info. 

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/query-overview#8]

**Comment by jwildfire** [comment]
Test Notes: Confirm that detailed field/form description appears when mousing over short field/form name on y-axis.

**Comment by jwildfire** [comment]
Use the following settings with our standard queries.csv data set: `{"formDescription_col":"formDescription","fieldDescription_col":"fieldDescription"}`

**Comment by jwildfire** [comment]
@brittsikora ready for testing in CAT with version = 'v1.0.0-dev' and data = 'queries/queries.csv'

**Comment by brittsikora** [comment]
Expected Result: Hovered over a form and form description appeared; hovered over a field and a field description appeared.
![8](https://cloud.githubusercontent.com/assets/14914918/25725139/be676ac8-30ec-11e7-95eb-874f6bc3356e.png)
![8_2](https://cloud.githubusercontent.com/assets/14914918/25725142/bf826b74-30ec-11e7-8e68-3e200fe23231.png)



Outcome: Pass
