### ISSUE TITLE
"Show First N Groups" is set to "All" but Chart Displays "X More" on Y-Axis

### ISSUE THREAD

**Issue by emmorris** [RhoInc/query-overview#86]
In certain situations the chart indicates that there are "X More" items that could be displayed on the y-axis even though the setting is set to show all.  

An example exists in RhoMAP Test for ITN058AI where "Show First N Groups" is set to "All" but the chart has text stating "and 7 more" on the y-axis.

**Comment by jwildfire** [comment]
Would probably be good to document how to reproduce this one ...
