### ISSUE TITLE
Dynamically adjust x-axis range when selecting "Grouped" for bar arrangement

### ISSUE THREAD

**Issue by emmorris** [RhoInc/query-overview#87]
![image](https://user-images.githubusercontent.com/23057086/45181542-c62c7280-b1ec-11e8-9728-21d2906467e3.png)

As you can see in the screenshot, the x-axis is abnormally large for the size of the bars displayed.  It should adjust based on the size of the bars.  This bug seems to be introduced when the user chooses "Grouped" in the bar arrangement toggle.

This was found by DMEDS and they would like it to be addressed in the next version.

**Comment by jwildfire** [comment]
Looks like the x-axis domain for grouped bars isn't being updated when the legend filter changes. Might be an easy fix ... or might be a webcharts bug ...

**Comment by jwildfire** [comment]
I'm about 75% sure this is a webcharts issue buried in the messy data processing section for the `draw()` function. Looks like [draw/consiolidateData/makeNest](https://github.com/RhoInc/Webcharts/tree/master/src/chart/draw/consolidateData/makeNest) has custom code calculates the domains when `arranged=stacked`, but falls back to a default logic when `arranged=grouped`.

**Comment by jwildfire** [comment]
Nah - ignore that noise above. Problem is almost definitely in './onPreprocess/updateRangeBand'. Will leave it for @samussiah. I think we just need to use filtered data to calculate max. Something like this: 

```
var subgroup_sizes = d3.nest()
.key(d => d[this.config.y.column] +"|"+ d[this.config.color_by])
.rollup(d =>d.length)
.entries(this.filtered_data);
var max_subgroup = d3.max(subgroup_sizes,d=>d.values}
```

**Comment by pburnsdata** [comment]
@samussiah @jwildfire hmm I'm not sure filtered_data is available until datatransform, but could just move it in there. I understand why we change this.config.range_band here, but why do we need to nest etc? I get the idea intuitively but It seems like the x domains adjust accordingly without that part. I'll post an example to chat. Sorry if this is obvious

**Comment by jwildfire** [comment]
Filtered data isn't available until on draw i think. You might be right though. Just deleting the x_dom calculation might work ...
