### ISSUE TITLE
In RhoMAP data listing is cut off and horizontal scroll bar is required

### ISSUE THREAD

**Issue by emmorris** [RhoInc/query-overview#88]
DMEDS has found that the data listing below the chart is cut off when it is displayed on RhoMAP.  This results in a horizontal scroll bar that is displayed all the way at the bottom of the listing.  They find this to be painful particularly with charts/listings that take up a lot of vertical space.

Ideas:

- Click and drag feature

- Floating scroll bar

Final decision: add horizontal scroll bar between the chart and the data listing so that the user can scroll while still seeing the column headers within the data listing

Note: They would also like to remove columns that are repetitive like fieldoid and fieldname.  Removing those could eliminate the scroll bar in some or all situations, so we may have an alternative solution once we try that out.

# Test Notes:
Either:
- Upload a dataset with a bunch of extra column and verify that the scroll bar appears and works as expected. The attached listing should not go off the page to the right.
- Scroll in on your browser until the listing wouldn't fit on the page and verify that the scroll bar appears and works as expected. The attached listing should not go off the page to the right.

**Comment by jwildfire** [comment]
Pretty sure that any of those solutions would require server-side RhoMap updates. cc: @rbudrevich

**Comment by pburnsdata** [comment]
Spencer had a good idea for fixing this we were able to figure this out.

**Comment by danedexF5** [comment]
Bootstap getting clicked on takes the scroll bar out right now. This should be resolved before we put it in RhoMap since RhoMap uses Bootstrap. There must be some conflicting style that is overriding the new scroll bar.

**Comment by pburnsdata** [comment]
@danedexF5 This might actually be okay - it only adds the scrollbar on top if the table doesn't fit on the page. Try uploading a larger dataset - I'll send one in chat or email since I've already got it. If the scroll bar still doesn't show up - then probably need to change something. The real issue is if it runs off the page and out of sight without providing a scroll bar.

**Comment by danedexF5** [comment]
@pburnsdata gotcha, yea this looks good then. Scroll bar working as expected with the larger data set.
